### ISSUE TITLE
Error in the callsign validation RegEx

### ISSUE THREAD

**Issue by VE3NEA** [KC3PIB/WsjtxUtils#15]
There is an error in the callsign validation regex that I provided, this error prevents matching the callsigns that start with "O". To fix it, please remove "N" from the first two lines of the expression. These lines should look like this:
```
            @"^(?<portableprefix>(?:(?:[A-PR-Z](?:(?:[A-Z](?:\d[A-Z]?)?)|(?:\d[\dA-Z]?))?)|(?:[2-9][A-Z]{1,2}\d?))\/)?" +
            // prefix
            @"(?<callprefix>(?:(?:[A-PR-Z][A-Z]?)|(?:[2-9][A-Z]{1,2}))\d)" +
```
Also, the regex allows up to 6 letters in the suffix, which is usually enough, but on the rare occasions there are callsigns with more letters, like `VC9CATGIRL` that was on the air today. To catch such callsigns, you may want to increase the max. letter count to 7:
```
 @"(?<callsuffix>\d{0,3}[A-Z]{1,7})" +
```

**Comment by KC3PIB** [comment]
I have updated the callsign regex with these changes and added a few more test cases. It looks like the suffix should also be increased to 8 characters to support callsigns like [OH4STAYHOME](https://www.qrz.com/db/OH4STAYHOME).
